language: android
android:
  components:
  - build-tools-23.0.1
  - android-22
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository
script:
- "./gradlew :app:assembleDebug"
deploy:
  provider: releases
  api_key:
    secure: Lxy+BDj7o/fmMkaYDABxA2321ya4qKgtgwPceiCaAWhP0yn6XOfu6bVQ8HKafYpHJH529qwK8aPES3rNa7zsOTg+vC9ZyLyJJcwTB28BGqsJRbUIMktzQcCHee/trx/24CiMZrgNq393HEFF3AjgQ5lxEzrRO9jaxFvpwf+uzrUrRve6xJRtS95iVPKCNt7O8zYr7r/nXd/NuDGsWOZ4GcmeCXLLvUtbsotLtu45teTBmnAlpOg9SEJ3SPMeL2IJ2QaplL0fxzJSCbH3KojpyN/eFpFkwYThHA8K+1k4GePS4vMg2dcHPFzLX2VjJOl61zZJRG7oicdvVT7pm5j4+vYtm0opux4ZRLBL70DKvYPAjtdxy/hD/ERwutt/gmgJYK0PF/QMEv/51QNtPqQPDHVf3eF1FqQ/LOD/FXweQDwmJEsOfhu3tn6ei1MwAEVyDyaae3f+w7usRsyFIiHAK+i592W7Tjh3rpHYftxt7M05ZCi7WbfdioKySBHTDgg8oUTWtplVa2EHV+THoyBmUA5qzkxgc6vrwTMQN76KeEWKIpUp1m7g1dttXWXFBMHyeAta2/qTXGp/lulhxNiv/rCAk2kjUabLx6I1n/aX/10gSS+gwUC5JNOJTN6jSLPYeFEZ8Ejr4r8m3nAUpE5iFwpOucmDj5qGSGXomCNZpd8=
  file: 'app/build/outputs/apk/app-Debug.apk'
  skip_cleanup: true
  on:
    tags: trueâ€¨
    all_branches: true
    repo: liyuzhao/helpdeskdemo-android
